application: notuxnobux
module: default
version: v1
runtime: go
api_version: go1

handlers:
# for letsencrypt
- url: /.well-known/acme-challenge
  static_dir: acme

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /elm-app.js
  static_files: elm-app.js
  upload: elm-app.js
  secure: always

- url: /(.*)
  script: _go_app
  secure: always
